<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => '泰瑞城',
  'url' => 'http://123.206.14.75',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\" style=\\"text-align:center;\\">	<p class=\\"links\\">		<a href=\\"\\">关于我们</a>|<a href=\\"\\">常见问题</a>|<a href=\\"\\">安全交易</a>|<a href=\\"\\">购买流程</a>|<a href=\\"\\">如何付款</a>|<a href=\\"\\">联系我们</a> 	</p>	<p class=\\"copyright\\">		<br /></p></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => '泰瑞城',
  'index_seo_keywords' => '泰瑞城,莫桑石',
  'index_seo_description' => '授权官方网站',
  'goods_no_pre' => 'SD',
  'commission' => '',
  'store_num_warning' => '1',
  'reg_option' => '0',
  'index_slide' => 'a:2:{i:0;a:3:{s:4:"name";s:8:"24234234";s:3:"url";s:68:"http://123.206.14.75/index.php?controller=site&action=products&id=96";s:3:"img";s:39:"upload/2018/05/26/20180526051202985.jpg";}i:1;a:3:{s:4:"name";s:2:"33";s:3:"url";s:2:"33";s:3:"img";s:39:"upload/2018/05/26/20180526051446885.jpg";}}',
  'guide_name' => 
  array (
    0 => '产品官网',
    1 => '后台管理',
    2 => '商家管理',
  ),
  'guide_link' => 
  array (
    0 => '123.206.14.75',
    1 => 'systemadmin/index',
    2 => 'seller/index',
  ),
)?>